name: Publish Post to Blogger

on:
  push:
    branches:
      - main
    paths:
      - 'posts/en/**/*.html'
  workflow_dispatch:


env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to support changed files detection

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm init -y
          npm install googleapis

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: posts/en/**/*.html

      - name: Publish posts
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Publishing: $file"
            node scripts/publish.js "$file"
            sleep 2
          done
